"""Generate a starter YAML suite from a server's advertised tools."""

from __future__ import annotations

import os
import re
import shlex
from pathlib import Path
from typing import Any

import yaml

from mcp_rig.client import ServerSpec, ToolInfo
from mcp_rig.lint import looks_side_effecting

SIDE_EFFECT_TAG = "side-effect"
DESCRIPTION_LIMIT = 100
_SCALAR_PLACEHOLDERS = {
    "string": "",
    "integer": 0,
    "number": 0,
    "boolean": False,
    "array": [],
    "null": None,
}


def scaffold_suite(server: ServerSpec, tools: list[ToolInfo], suite_path: Path | None = None) -> str:
    """Render a runnable suite with one placeholder case per tool."""
    lines = [
        "# Generated by `mcp-rig init`. Replace placeholder arguments and add",
        "# expectations; each case currently only requires a successful call.",
        *_server_lines(server, suite_path),
        "",
        "tests:",
    ]
    for tool in tools:
        lines.append("")
        description = " ".join(tool.description.split())
        if description:
            if len(description) > DESCRIPTION_LIMIT:
                description = description[: DESCRIPTION_LIMIT - 1] + "…"
            lines.append(f"  # {description}")
        lines.append("  # TODO: replace placeholder arguments and add expectations.")
        lines.append(f"  - name: {_scalar(tool.name)}")
        lines.append(f"    call: {_scalar(tool.name)}")
        if _is_side_effecting(tool):
            lines.append(f"    tags: [{SIDE_EFFECT_TAG}]")
        args = placeholder_arguments(tool.input_schema)
        if args:
            lines.append(f"    args: {_flow(args)}")
    return "\n".join(lines) + "\n"


def placeholder_arguments(schema: dict[str, Any]) -> dict[str, Any]:
    """Build typed placeholders for a tool's required parameters."""
    properties = schema.get("properties")
    required = schema.get("required")
    if not isinstance(properties, dict) or not isinstance(required, list):
        return {}
    return {
        name: placeholder_value(properties.get(name, {}))
        for name in required
        if isinstance(name, str)
    }


def placeholder_value(schema: Any) -> Any:
    """Return a value of the schema's type, preferring its default, const, or first enum value."""
    if not isinstance(schema, dict):
        return None
    if "default" in schema:
        return schema["default"]
    if "const" in schema:
        return schema["const"]
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return schema["enum"][0]
    for key in ("anyOf", "oneOf"):
        options = schema.get(key)
        if isinstance(options, list):
            usable = [option for option in options if not (isinstance(option, dict) and option.get("type") == "null")]
            if usable:
                return placeholder_value(usable[0])
    kind = schema.get("type")
    if isinstance(kind, list):
        kind = next((item for item in kind if item != "null"), "null")
    if kind == "object":
        return placeholder_arguments(schema)
    return _SCALAR_PLACEHOLDERS.get(kind)


def header_variables(server: ServerSpec) -> dict[str, str]:
    """Environment variable names that generated suites read header values from."""
    return {name: "MCP_" + re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper() for name in server.headers}


def _server_lines(server: ServerSpec, suite_path: Path | None) -> list[str]:
    if server.is_remote:
        lines = ["server:", f"  url: {_scalar(server.url)}"]
        if server.transport != "streamable-http":
            lines.append(f"  transport: {server.transport}")
        variables = header_variables(server)
        if variables:
            lines.append("  headers:")
            for name, variable in variables.items():
                lines.append(f"    {_scalar(name)}: {_scalar('${' + variable + '}')}")
        return lines
    cwd = _relative_cwd(suite_path)
    if cwd is None and not server.env and not server.inherit_env:
        return [f"server: {_scalar(_command_line(server))}"]
    lines = ["server:", f"  command: {_scalar(server.command)}"]
    if server.args:
        lines.append(f"  args: {_flow(server.args)}")
    if cwd is not None:
        lines.append(f"  cwd: {_scalar(cwd)}")
    if server.env:
        # Values may be secrets, so the suite reads them from the environment it runs in.
        lines.append("  env:")
        for name in server.env:
            lines.append(f"    {name}: {_scalar('${' + name + '}')}")
    if server.inherit_env:
        lines.append(f"  inherit_env: {_flow(list(server.inherit_env))}")
    return lines


def _relative_cwd(suite_path: Path | None) -> str | None:
    """Keep the server starting in today's directory once the suite lives elsewhere."""
    if suite_path is None:
        return None
    suite_dir = suite_path.resolve().parent
    current = Path.cwd().resolve()
    if suite_dir == current:
        return None
    return Path(os.path.relpath(current, suite_dir)).as_posix()


def _command_line(server: ServerSpec) -> str:
    return shlex.join([server.command, *server.args])


def _is_side_effecting(tool: ToolInfo) -> bool:
    return looks_side_effecting(tool) or tool.annotations.get("destructiveHint") is True


def _scalar(value: str) -> str:
    return yaml.safe_dump(value, default_flow_style=True, allow_unicode=True, width=10_000).removesuffix(
        "\n...\n"
    ).strip()


def _flow(value: Any) -> str:
    return yaml.safe_dump(value, default_flow_style=True, allow_unicode=True, sort_keys=False, width=10_000).strip()
